<?php

$plugin = array(
  'title' => t('Utec site template blog detail'),
  'theme' => 'utec_site_template_blog_detail',
  'icon' => 'utec-site-template-blog-detail.png',
  'category' => 'Utec Theme',
  'regions' => array(
    'header' => t('Header'),
    'menu-mobile' => t('Menu Mobile'),
    'header-bottom' => t('Header Bottom'),
    'left-side' => t('Left Side'),
    'right-side' => t('Right Side'),
    'footer' => t('Footer'),
  ),
);

