// Generated by CoffeeScript 1.8.0
(function() {
  $(document).ready(function() {
    var $container;
    $container = $('.grid-list-centered');
    $container.imagesLoaded(function() {
      $container.isotope({
        itemSelector: '.mb-ch-14'
      });
    });
  });

}).call(this);
