// Generated by CoffeeScript 1.8.0
(function() {
  $(document).ready(function() {
    $('.disable-anchors a').click(function(e) {
      e.preventDefault();
    });
    $('div[data-href]').click(function(e) {
      console.log($(this).data('href'));
      document.location.replace($(this).data('href'));
    });
  });

}).call(this);
