// Generated by CoffeeScript 1.8.0
(function() {
  $(document).ready(function() {
    var $siteMenu;
    $siteMenu = $('.site-menu');
    $('.disable-anchors a').click(function(e) {
      e.preventDefault();
    });
    $('[data-href]').click(function(e) {
      console.log($(this).data('href'));
      document.location.replace($(this).data('href'));
    });
    $('.menu-trigger').click(function(e) {
      e.preventDefault();
      $('.site-wrapper').toggleClass('menu-on');
      $('body').toggleClass('scroll-y-off');
    });
    $('#edit-submit.form-submit').addClass('atm-buscar');
    $('.language-link').addClass('atm-idiomas');
  });

}).call(this);
