// Generated by CoffeeScript 1.8.0
(function() {
  $(document).ready(function() {
    var makeScramble, textArr, textEN, textES, tl, tlText;
    textES = $('#text-switcher-word').length;
    textEN = $('#text-switcher-word-en').length;
    tlText = '';
    textArr = [];
    if (textES) {
      tlText = '#text-switcher-word';
      textArr = ['bienestar', 'innovación', 'diseño'];
    } else {
      tlText = '#text-switcher-word-en';
      textArr = ['well-being', 'innovation', 'design'];
    }
    tl = new TimelineMax();
    makeScramble = function() {
      tl.to(tlText, 1, {
        scrambleText: {
          text: textArr[0],
          chars: "lowerCase",
          speed: 1,
          tweenLength: true,
          ease: Linear.easeNone
        }
      });
      tl.to(tlText, 1, {
        scrambleText: {
          text: textArr[1],
          chars: "lowerCase",
          speed: 1,
          tweenLength: true,
          ease: Linear.easeNone
        }
      });
      tl.to(tlText, 1, {
        scrambleText: {
          text: textArr[2],
          chars: "lowerCase",
          speed: 1,
          tweenLength: true,
          ease: Linear.easeNone
        }
      });
      setTimeout(function() {
        makeScramble();
      }, 1500);
    };
    makeScramble();
  });

}).call(this);
