// Generated by CoffeeScript 1.8.0
(function() {
  $(document).ready(function() {
    var $bodyForm, $button;
    $button = $('.body button[type="submit"]');
    $bodyForm = $('.body form');
    $bodyForm.on('submit', function(e) {
      $button.append('<span class="spinner animated rotateIn infinite icon-spinner9"></span>');
    });
    console.log($button);
  });

}).call(this);
