// Generated by CoffeeScript 1.8.0
(function() {
  $(document).ready(function() {
    var $siteMenu, $siteMenuClose, $siteMenuContent, $siteWrapper;
    $siteMenu = {
      navMain: $('.site-menu .nav-main'),
      items: $('.site-menu .nav-main li'),
      anchor: $('.site-menu .nav-main li a')
    };
    $siteMenuContent = {
      siteMenu: $('.site-menu-content'),
      titleItems: $('.site-menu-content .titles li'),
      contentWrapperLists: $('.site-menu-content .content-wrapper ul')
    };
    $siteWrapper = $('.site-wrapper');
    $siteMenuClose = $('.site-menu-close');
    $siteMenu.navMain.on('mouseover', 'li', function(event) {
      var el;
      if ($siteWrapper.hasClass('on-home')) {
        $siteWrapper.removeClass('on-home');
        $siteWrapper.removeClass('toggle-nav');
      }
      $siteWrapper.removeClass('toggle-nav');
      $siteMenuClose.removeClass('hidden');
      $('body').css({
        overflow: 'hidden'
      });
      el = $(this);
      el.mousemove(function(e) {
        var getOffsetY, x, y;
        getOffsetY = function() {
          return el.find('a').offset().top;
        };
        x = e.offsetX != null ? e.offsetX : e.screenX;
        y = e.offsetY != null ? e.offsetY : getOffsetY();
        if (x > 61) {
          console.log('Element Y: ' + y + ' Screen Y: ' + e.screenY);
          $siteMenuContent.titleItems.eq(el.index()).css({
            'z-index': '1000'
          });
          $siteMenuContent.contentWrapperLists.eq(el.index()).css({
            'z-index': '1000'
          });
        } else {
          $siteMenuContent.titleItems.css({
            'z-index': '30'
          });
          $siteMenuContent.contentWrapperLists.css({
            'z-index': '30'
          });
          $siteMenuContent.contentWrapperLists.css({
            'z-index': '30 '
          });
        }
        if (y > 1 && y < 62) {
          $siteMenuContent.titleItems.eq(el.index()).css({
            'z-index': '1000'
          });
          $siteMenuContent.contentWrapperLists.eq(el.index()).css({
            'z-index': '1000'
          });
        } else {
          $siteMenuContent.titleItems.css({
            'z-index': '30'
          });
          $siteMenuContent.contentWrapperLists.css({
            'z-index': '30'
          });
        }
      });
    });
    $siteMenuContent.contentWrapperLists.on('mouseover', function() {
      $siteMenu.items.eq($(this).index()).find('a').addClass('active');
    });
    $siteMenuContent.contentWrapperLists.on('mouseleave', function() {
      $siteMenu.items.eq($(this).index()).find('a').removeClass('active');
    });
    $siteMenuClose.on('mouseover', function() {
      $siteWrapper.addClass('toggle-nav');
      $(this).addClass('hidden');
      $siteMenu.anchor.removeClass('active');
      $('body').css({
        overflow: 'auto'
      });
    });
  });

}).call(this);
