// Generated by CoffeeScript 1.8.0
(function ($) {
  Drupal.behaviors.exampleModule = {
    attach: function (context, settings) {
      // $('.example', context).click(function () {
      //   $(this).next('ul').toggle('show');
      // });
      (function() {
        $(document).ready(function() {
          var $siteMenu, $siteMenuClose, $siteMenuContent, $siteWrapper, getDocHeight;
          $siteMenu = {
            navMain: $('.site-menu .nav-main'),
            items: $('.site-menu .nav-main li'),
            anchor: $('.site-menu .nav-main li a')
          };
          $siteMenuContent = {
            siteMenu: $('.site-menu-content'),
            titleItems: $('.site-menu-content .titles li'),
            contentWrapperLists: $('.site-menu-content .content-wrapper ul')
          };
          $siteWrapper = $('.site-wrapper');
          $siteMenuClose = $('.site-menu-close');
          $siteMenuClose.css({
            'height': $(document).height()
          });
          $('.site-menu .nav-main li, .site-menu-content .content-wrapper ul').hover(function() {
            var $siteMenuContentItem, $siteMenuItem;
            console.log($(this).index());
            $siteMenuItem = $('.site-menu .nav-main li');
            $siteMenuContentItem = $('.site-menu-content .content-wrapper ul');
            if ($siteWrapper.hasClass('on-home')) {
              $siteWrapper.removeClass('on-home');
              $siteWrapper.removeClass('toggle-nav');
            }
            $siteWrapper.removeClass('toggle-nav');
            $siteMenuClose.removeClass('hidden');
            $('body').css({
              overflow: 'hidden'
            });
            $siteMenuContent.titleItems.eq($(this).index()).css({
              'z-index': 1000
            });
            $siteMenuContentItem.eq($(this).index()).css({
              'z-index': 1000
            });
          }, function() {
            $siteMenuContent.titleItems.css({
              'z-index': 30
            });
            $siteMenuContent.contentWrapperLists.css({
              'z-index': 30
            });
          });
          $siteMenuContent.contentWrapperLists.hover(function() {
            $siteMenu.items.eq($(this).index()).find('a').addClass('active');
          }, function() {
            $siteMenu.items.eq($(this).index()).find('a').removeClass('active');
          });
          $siteMenuClose.on('mouseover', function() {
            $siteWrapper.addClass('toggle-nav');
            $(this).addClass('hidden');
            $siteMenu.anchor.removeClass('active');
            $('body').css({
              overflow: 'auto'
            });
          });
          getDocHeight = function() {
            var D;
            D = document;
            return Math.max(D.body.scrollHeight, D.documentElement.scrollHeight, D.body.offsetHeight, D.documentElement.offsetHeight, D.body.clientHeight, D.documentElement.clientHeight);
          };
          $(window).scroll(function() {
            if ($(window).scrollTop() + $(window).height() === getDocHeight()) {
              $siteWrapper.removeClass('on-home');
              $siteWrapper.addClass('on-footer');
            } else {
              $siteWrapper.removeClass('on-footer');
            }
          });
        });

      }).call(this);
    }
  };
})(jQuery);

