// Generated by CoffeeScript 1.8.0
(function() {
  $(document).ready(function() {
    var makeScramble, tl;
    tl = new TimelineMax();
    makeScramble = function() {
      tl.to("#text-switcher-word", 3, {
        scrambleText: {
          text: "bienestar",
          chars: "lowerCase",
          revealDelay: 0.5,
          tweenLength: false,
          ease: Linear.easeNone
        }
      });
      tl.to("#text-switcher-word", 3, {
        scrambleText: {
          text: "innovación",
          chars: "lowerCase",
          revealDelay: 0.5,
          tweenLength: false,
          ease: Linear.easeNone
        }
      });
      tl.to("#text-switcher-word", 3, {
        scrambleText: {
          text: "diseño",
          chars: "lowerCase",
          revealDelay: 0.5,
          tweenLength: false,
          ease: Linear.easeNone
        }
      });
      setTimeout(function() {
        makeScramble();
      }, 1500);
    };
    makeScramble();
  });

}).call(this);
