<?php

function _metatags_panemessages_var($var_name, $new_val = NULL) {
  $vars = &drupal_static(__FUNCTION__, array());

  // If a new value has been passed
  if ($new_val) {
    $vars[$var_name] = $new_val;
    // print_r($vars);
  }
  return isset($vars[$var_name]) ? $vars[$var_name] : NULL;
}

function metatags_panemessages_preprocess_node(&$variables){
  $variables['og_description'] = _metatags_panemessages_var('og_description');
    kpr($variables);

}

function metatags_panemessages_preprocess_page(&$variables){

	  // kpr($variables);
	$og_title = $variables['page']['content']['metatags']['global']['og:title'];
	$og_description = $variables['page']['content']['metatags']['global']['og:description']['#attached']['drupal_add_html_head'][0][0]['#value'];
	// die($og_description);
	$variables['og_description'] = _metatags_panemessages_var('og_description', $og_description);
	// $variables['og_description'] = _utec_theme_var('og_description', $og_description);
}

