<?php

/**
 * Implements hook_entity_info().
 */
function netsuite_form_builder_entity_info() {
  return array(
    'netsuite_block' => array(
      'label' => t('Netsuite Block'),
      'base table' => 'netsuite_block',
      'entity keys' => array(
        'id' => 'nsid',
      ),
    ),
  );
}

/**
 * Implements hook_init().
 */
function netsuite_form_builder_init() {
  $node = menu_get_object();
  if (!empty($node)) {
    if ($node->type == 'thank_you_page') {
      drupal_add_js(drupal_get_path('module', 'netsuite_form_builder') . '/js/utec_netsuite_datalayer.js', 'file');
      drupal_add_css(drupal_get_path('module', 'netsuite_form_builder') . '/css/netsuite_form_builder.css', 'file');
    } 
  }
}

/**
 * Implements hook_menu().
 */
function netsuite_form_builder_menu() {

  $items['netsuite-nested-frame-career'] = array(
    'title' => 'Proxy',
    'page callback' => 'netsuite_form_builder_nested_frame',
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * javascript function that adds to the nested frame.
 */
function netsuite_form_builder_nested_frame() {
  $output = '<!DOCTYPE html>
  <html>
    <head>
      <script>
        window.onload = function (){
          var result, pairs;
          var querystring = window.location.href.split("?")[1] || false;
          //Ensure querystring exists and has valid result identifier
          if(!querystring || querystring.indexOf("result=") === -1){ return false; }
          //Ensure all ampersands are single (not entities) so we can split using "&"
          querystring = querystring.replace(/&/g, "&");
          //Create an array of value pairs. This gives us flexibility
          //to add more items to the querystring later.
          pairs = querystring.split("&");
          result = pairs[0].replace("result=", "");
          top.netsuite_form_builder_set_career(result);
        };
      </script>
    </head>
    <body>
    </body>
  </html>';
  print $output; exit;
}

/**
 * Implements hook_block_info().
 */  
function netsuite_form_builder_block_info() {
  $blocks = array();

  if (!empty($blocks)) {
    return $blocks;
  }

  $blocks = array();
  $netsuite_blocks = entity_load('netsuite_block');
  foreach ($netsuite_blocks as $netsuite_block) {
    $blocks[$netsuite_block->delta] = array(
      'info' => $netsuite_block->title,
    );
  }

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function netsuite_form_builder_block_view($delta = '') {
  drupal_add_js(drupal_get_path('module', 'netsuite_form_builder') . '/js/netsuite_form_builder_set_career_datalayer.js', 'file');
  global $language;  

  $node = menu_get_object();

  if ($node == NULL) {
    $nid = netsuite_form_builder_variable('node');
    $node = node_load($nid);
  }

  $block = array();
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'netsuite_block');
  $query->propertyCondition('delta', $delta);
  $result = $query->execute();
  $object_content_id_netsuite_block = array_shift($result['netsuite_block']);
  $netsuite_block = entity_load('netsuite_block', array($object_content_id_netsuite_block->nsid));

  $into_netsuite_block = array_shift($netsuite_block);
  $block['subject'] = $into_netsuite_block->title;

  if (@unserialize($into_netsuite_block->path_netsuite) !== FALSE) {
    $paths = unserialize($into_netsuite_block->path_netsuite);
    $path = $paths[$language->language];
  }
  else {
    $path = $into_netsuite_block->path_netsuite; 
  }

  // Pasando variables php a js
  if (@unserialize($into_netsuite_block->parameters_datalayer) !== FALSE) {
    $parameters_datalayer = unserialize($into_netsuite_block->parameters_datalayer);
    $form = $parameters_datalayer['form'];
    $course = $parameters_datalayer['curso'];
  }
  else {
    $form = '';
    $course = '';
  }

  if (isset($_GET['firstname'])) {
    $usuario_estado = 'identificado';
  }
  else {
    $usuario_estado = 'no-identificado';
  }

  $courseValue = token_replace($course, array('node' => $node));
  $datalayer_settings = array(
    'form' => $form,
    'curso' => $courseValue,
    'usuario_estado' => $usuario_estado,
  );

  drupal_add_js(array('netsuite_form_builder' => $datalayer_settings), 'setting');

  drupal_add_js("var dataLayer = [];dataLayer.push({'nombre_curso': '" . $courseValue . "'});", array('scope' => 'header', 'type' => 'inline'));

  $params = unserialize($into_netsuite_block->parameters);
  $params_in_path = '';

  $referer = $_SERVER['HTTP_REFERER'];
    
  // Para que funcione el medio de origen se debe de agregar 
  // custevent3 o custentity69 al paramenters de la tabla netsuite_block.
  $origin = '';
  if(trim($referer) == '') {
    $origin = 'Direct';
  }
  else if(strpos($referer, 'google') !== FALSE) {
    $origin = 'Search';
  }
  else if(strpos($referer, 'r.search.yahoo') !== FALSE) {
    $origin = 'Search';
  }
  else if(strpos($referer, 'bing') !== FALSE) {
    $origin = 'Search';
  }
  else if(strpos($referer, $_SERVER['SERVER_NAME']) !== FALSE) {
    $origin = 'Organico';
  }
  else {
    $origin = 'Referral';
  }

  if (isset($params['custentity69'])) {
    $params['custentity69'] = $origin;
  }
  
  if (isset($params['custevent3'])) {
    $params['custevent3'] = $origin;
  }

  $params = array_merge($params, $_GET);
  unset($params['q']);
  
  foreach ($params as $key => $param) {
    if ($node != NULL) {
      $params_in_path .= '&' . $key . '=' . token_replace($param, array('node' => $node));
    }
    else {
      $params_in_path .= '&' . $key . '=' . token_replace($param, array('node' => $node));
    }
  }
  $utf8URLEncoding = array('á', 'é', 'í', 'ó', 'ú', 'Á', 'É', 'Í', 'Ó', 'Ú', 'ñ', 'Ñ', ' ');
  $winURLEnconding = array('%E1', '%E9', '%ED', '%F3', '%FA', '%C1', '%C9', '%CD', '%D3', '%DA', '%F1', '%D1', '%20');

  $params_in_path = str_replace($utf8URLEncoding, $winURLEnconding, $params_in_path);

  $variables = array(
    'path_netsuite' => $path,
    'parameters' => $params_in_path,
  );

  $output = theme('netsuite_form_builder_block', $variables);
  $block['content'] = $output;

  return $block;
}

/**
 * Implements hook_theme().
 */
function netsuite_form_builder_theme($existing, $type, $theme, $path) {
  return array(
    'netsuite_form_builder_block' => array(
      'template' => 'netsuite-form-builder-block',
    ),
  );
}

/**
 * Load a single record.
 *
 * @param $id
 *    The id representing the record we want to load.
 */
function netsuite_form_builder_load($id, $reset = FALSE) {
  return netsuite_form_builder_load_multiple(array($id), array(), $reset);
}

/**
 * Load multiple records.
 */
function netsuite_form_builder_load_multiple($ids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('netsuite_block', $ids, $conditions, $reset);
}

/**
 * Function to save the value of the variable.
 */
function netsuite_form_builder_variable($name, $value = NULL) {
  $var = &drupal_static(__FUNCTION__);
  if (!is_null($value)) {
    $var[$name] = $value;
    return $value;
  }

  if (!isset($var[$name])) {
    return NULL;
  }
  
  return $var[$name];
}
