<?php

// $rate = '';
module_load_include('module', 'era');
$pen = era_get_rates();

	$rate = $pen['rates']['PEN'];
	// die(print_r($variables));
// function currency_send_rate($rate){
// 	// global $rate;
// 	// die(print_r($rate));
// 	return $rate;
// }

// $rate = $pen['rates']['PEN'];
	// die(print_r($rate));

function currency_exchange_preprocess_node(&$variables) {
	global $rate;
	// $rate2 = currency_send_rate($rate);
	die(print_r($rate));
	 // Specific to 'foo'.
  // if ($hook == 'foo') {
    
	  $variables['xpen'] = $rate;
  
	// print_r($variables);
}









