<?php

module_load_include('module', 'era');
$pen = era_get_rates();

function currency_send_rate($pen){
	return $rate = $pen['rates']['PEN'];
}

// $rate = $pen['rates']['PEN'];
	// die(print_r($rate));


function currency_exchange_view($node, $view_mode){
	// die('entro');
	// $node = entity_load('node', 1352);
	// field_tipo_de_cambio
	// $node->pen['und']['0']['value'] = $rate;
	kpr($node);

}

function currency_exchange_preprocess(&$variables, $rate) {
	$rate = currency_send_rate($pen);
  $variables['xpen'] = $rate;
	die(print_r($variables));
}









